apiVersion: v1
kind: Service
metadata:
  name: addok-service
spec:
  selector:
    app: addok
  ports:
    - protocol: TCP
      port: 7878
      targetPort: 7878
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: addok-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
